# Generated by Django 3.2.12 on 2022-04-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    
    dependencies = [
        ('portfolio', '0004_auto_20220402_2244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facts',
            new_name='Fact',
        ),
        migrations.RenameModel(
            old_name='ProgLanguages',
            new_name='ProgLanguage',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='fact',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='language',
        ),
        migrations.AddField(
            model_name='developer',
            name='facts',
            field=models.ManyToManyField(to='portfolio.Fact'),
        ),
        migrations.AddField(
            model_name='developer',
            name='languages',
            field=models.ManyToManyField(to='portfolio.ProgLanguage'),
        ),
    ]
